#!/usr/bin/env bash
# This script tells the story of passwd

while IFS=':' read -r username _ userid groupid _ homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo -e "$userid's place is protected by the passcode 'PASSWORD', more info about the user here: USER $userid INFO"
done < /etc/passwd
