#!/usr/bin/env bash
# This script tells the story of passwd

#!/bin/bash

while IFS=':' read -r username password userid groupid user_info homedir shell;
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "User ID's place is protected by the passcode PASSWORD, more info about the user here: USER $userid INFO"
done < /etc/passwd
