#!/usr/bin/env bash
# This script prints "Best School" 10 times with Hi added the 9th time

counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    counter=$((counter + 1))
done
