#!/usr/bin/env bash
# Script to be used with manage_my_process: Start, Stops, Restarts. 

argv1=$1
tmpfile="/var/run/my_process.pid"

strtLoop_n_crteFile()
{
    ./manage_my_process &
    echo "$!" > "$tmpfile"
}
killLoop_n_rmFile()
{
    sudo pkill -f "./manage_my_process"
    rm "$tmpfile"
}
case "$argv1" in
    start) echo "manage_my_process started"
        strtLoop_n_crteFile
        ;;
    stop) echo "manage_my_process stopped"
        killLoop_n_rmFile
        ;;
    restart) echo "manage_my_process restarted"
        killLoop_n_rmFile
        strtLoop_n_crteFile
        ;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
