#!/usr/bin/env bash
# script displays 'to infinity and beyond' with sleep 2 and 'i am invincible on receiving sigterm

altmessage()
{
	echo "I am invincinble!!!"
}
trap "altmessage" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
