#!/usr/bin/env bash
# script displays 'to infinity and beyond' with sleep 2 and 'i am invincible on receiving sigterm

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Register SIGTERM signal handler
trap 'handle_sigterm' SIGTERM

# Loop to display the message indefinitely
while :
do
    echo "To infinity and beyond"
    sleep 2
done
